/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* Radio Channel Frequency type
*/
public class CHANNEL_FREQUENCY {
   public static final int CHANNEL_FREQUENCY_2405MHZ = 4; /* Radio Channel Frequency 2405MHz | */
   public static final int CHANNEL_FREQUENCY_2406MHZ = 5; /* Radio Channel Frequency 2406MHz | */
   public static final int CHANNEL_FREQUENCY_2407MHZ = 6; /* Radio Channel Frequency 2407MHz | */
   public static final int CHANNEL_FREQUENCY_2408MHZ = 7; /* Radio Channel Frequency 2408MHz | */
   public static final int CHANNEL_FREQUENCY_2409MHZ = 8; /* Radio Channel Frequency 2409MHz | */
   public static final int CHANNEL_FREQUENCY_2410MHZ = 9; /* Radio Channel Frequency 2410MHz | */
   public static final int CHANNEL_FREQUENCY_2411MHZ = 10; /* Radio Channel Frequency 2411MHz | */
   public static final int CHANNEL_FREQUENCY_2412MHZ = 11; /* Radio Channel Frequency 2412MHz | */
   public static final int CHANNEL_FREQUENCY_2413MHZ = 12; /* Radio Channel Frequency 2413MHz | */
   public static final int CHANNEL_FREQUENCY_2414MHZ = 13; /* Radio Channel Frequency 2414MHz | */
   public static final int CHANNEL_FREQUENCY_2415MHZ = 14; /* Radio Channel Frequency 2415MHz | */
   public static final int CHANNEL_FREQUENCY_2416MHZ = 15; /* Radio Channel Frequency 2416MHz | */
   public static final int CHANNEL_FREQUENCY_2417MHZ = 16; /* Radio Channel Frequency 2417MHz | */
   public static final int CHANNEL_FREQUENCY_2418MHZ = 17; /* Radio Channel Frequency 2418MHz | */
   public static final int CHANNEL_FREQUENCY_2419MHZ = 18; /* Radio Channel Frequency 2419MHz | */
   public static final int CHANNEL_FREQUENCY_2420MHZ = 19; /* Radio Channel Frequency 2420MHz | */
   public static final int CHANNEL_FREQUENCY_2421MHZ = 20; /* Radio Channel Frequency 2421MHz | */
   public static final int CHANNEL_FREQUENCY_2422MHZ = 21; /* Radio Channel Frequency 2422MHz | */
   public static final int CHANNEL_FREQUENCY_2423MHZ = 22; /* Radio Channel Frequency 2423MHz | */
   public static final int CHANNEL_FREQUENCY_2424MHZ = 23; /* Radio Channel Frequency 2424MHz | */
   public static final int CHANNEL_FREQUENCY_2425MHZ = 24; /* Radio Channel Frequency 2425MHz | */
   public static final int CHANNEL_FREQUENCY_2426MHZ = 25; /* Radio Channel Frequency 2426MHz | */
   public static final int CHANNEL_FREQUENCY_2427MHZ = 26; /* Radio Channel Frequency 2427MHz | */
   public static final int CHANNEL_FREQUENCY_2428MHZ = 27; /* Radio Channel Frequency 2428MHz | */
   public static final int CHANNEL_FREQUENCY_2429MHZ = 28; /* Radio Channel Frequency 2429MHz | */
   public static final int CHANNEL_FREQUENCY_2430MHZ = 29; /* Radio Channel Frequency 2430MHz | */
   public static final int CHANNEL_FREQUENCY_2431MHZ = 30; /* Radio Channel Frequency 2431MHz | */
   public static final int CHANNEL_FREQUENCY_2432MHZ = 31; /* Radio Channel Frequency 2432MHz | */
   public static final int CHANNEL_FREQUENCY_2433MHZ = 32; /* Radio Channel Frequency 2433MHz | */
   public static final int CHANNEL_FREQUENCY_2434MHZ = 33; /* Radio Channel Frequency 2434MHz | */
   public static final int CHANNEL_FREQUENCY_2435MHZ = 34; /* Radio Channel Frequency 2435MHz | */
   public static final int CHANNEL_FREQUENCY_2436MHZ = 35; /* Radio Channel Frequency 2436MHz | */
   public static final int CHANNEL_FREQUENCY_2437MHZ = 36; /* Radio Channel Frequency 2437MHz | */
   public static final int CHANNEL_FREQUENCY_2438MHZ = 37; /* Radio Channel Frequency 2438MHz | */
   public static final int CHANNEL_FREQUENCY_2439MHZ = 38; /* Radio Channel Frequency 2439MHz | */
   public static final int CHANNEL_FREQUENCY_2440MHZ = 39; /* Radio Channel Frequency 2440MHz | */
   public static final int CHANNEL_FREQUENCY_2441MHZ = 40; /* Radio Channel Frequency 2441MHz | */
   public static final int CHANNEL_FREQUENCY_2442MHZ = 41; /* Radio Channel Frequency 2442MHz | */
   public static final int CHANNEL_FREQUENCY_2443MHZ = 42; /* Radio Channel Frequency 2443MHz | */
   public static final int CHANNEL_FREQUENCY_2444MHZ = 43; /* Radio Channel Frequency 2444MHz | */
   public static final int CHANNEL_FREQUENCY_2445MHZ = 44; /* Radio Channel Frequency 2445MHz | */
   public static final int CHANNEL_FREQUENCY_2446MHZ = 45; /* Radio Channel Frequency 2446MHz | */
   public static final int CHANNEL_FREQUENCY_2447MHZ = 46; /* Radio Channel Frequency 2447MHz | */
   public static final int CHANNEL_FREQUENCY_2448MHZ = 47; /* Radio Channel Frequency 2448MHz | */
   public static final int CHANNEL_FREQUENCY_2449MHZ = 48; /* Radio Channel Frequency 2449MHz | */
   public static final int CHANNEL_FREQUENCY_2450MHZ = 49; /* Radio Channel Frequency 2450MHz | */
   public static final int CHANNEL_FREQUENCY_2451MHZ = 50; /* Radio Channel Frequency 2451MHz | */
   public static final int CHANNEL_FREQUENCY_2452MHZ = 51; /* Radio Channel Frequency 2452MHz | */
   public static final int CHANNEL_FREQUENCY_2453MHZ = 52; /* Radio Channel Frequency 2453MHz | */
   public static final int CHANNEL_FREQUENCY_2454MHZ = 53; /* Radio Channel Frequency 2454MHz | */
   public static final int CHANNEL_FREQUENCY_2455MHZ = 54; /* Radio Channel Frequency 2455MHz | */
   public static final int CHANNEL_FREQUENCY_2456MHZ = 55; /* Radio Channel Frequency 2456MHz | */
   public static final int CHANNEL_FREQUENCY_2457MHZ = 56; /* Radio Channel Frequency 2457MHz | */
   public static final int CHANNEL_FREQUENCY_2458MHZ = 57; /* Radio Channel Frequency 2458MHz | */
   public static final int CHANNEL_FREQUENCY_2459MHZ = 58; /* Radio Channel Frequency 2459MHz | */
   public static final int CHANNEL_FREQUENCY_2460MHZ = 59; /* Radio Channel Frequency 2460MHz | */
   public static final int CHANNEL_FREQUENCY_2461MHZ = 60; /* Radio Channel Frequency 2461MHz | */
   public static final int CHANNEL_FREQUENCY_2462MHZ = 61; /* Radio Channel Frequency 2462MHz | */
   public static final int CHANNEL_FREQUENCY_2463MHZ = 62; /* Radio Channel Frequency 2463MHz | */
   public static final int CHANNEL_FREQUENCY_2464MHZ = 63; /* Radio Channel Frequency 2464MHz | */
   public static final int CHANNEL_FREQUENCY_2465MHZ = 64; /* Radio Channel Frequency 2465MHz | */
   public static final int CHANNEL_FREQUENCY_2466MHZ = 65; /* Radio Channel Frequency 2466MHz | */
   public static final int CHANNEL_FREQUENCY_2467MHZ = 66; /* Radio Channel Frequency 2467MHz | */
   public static final int CHANNEL_FREQUENCY_2468MHZ = 67; /* Radio Channel Frequency 2468MHz | */
   public static final int CHANNEL_FREQUENCY_2469MHZ = 68; /* Radio Channel Frequency 2469MHz | */
   public static final int CHANNEL_FREQUENCY_2470MHZ = 69; /* Radio Channel Frequency 2470MHz | */
   public static final int CHANNEL_FREQUENCY_2471MHZ = 70; /* Radio Channel Frequency 2471MHz | */
   public static final int CHANNEL_FREQUENCY_2472MHZ = 71; /* Radio Channel Frequency 2472MHz | */
   public static final int CHANNEL_FREQUENCY_2473MHZ = 72; /* Radio Channel Frequency 2473MHz | */
   public static final int CHANNEL_FREQUENCY_2474MHZ = 73; /* Radio Channel Frequency 2474MHz | */
   public static final int CHANNEL_FREQUENCY_2475MHZ = 74; /* Radio Channel Frequency 2475MHz | */
   public static final int CHANNEL_FREQUENCY_2476MHZ = 75; /* Radio Channel Frequency 2476MHz | */
   public static final int CHANNEL_FREQUENCY_2477MHZ = 76; /* Radio Channel Frequency 2477MHz | */
   public static final int CHANNEL_FREQUENCY_2478MHZ = 77; /* Radio Channel Frequency 2478MHz | */
   public static final int CHANNEL_FREQUENCY_2479MHZ = 78; /* Radio Channel Frequency 2479MHz | */
   public static final int CHANNEL_FREQUENCY_ENUM_END = 79; /*  | */
}
            