/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* EO/IR Camera Channel Mode Control flags (bitmask)
*/
public class CHANNEL_MODE_TYPE {
   public static final int RATE_CMD_NOT_DEPEND_FOV = 16; /* Rate Command does Not Depend on FOV(rate cmd depend on FOV : 0, rate cmd don't depend on FOV : 1) | */
   public static final int THERMAL_CHANNEL_ON = 128; /* Thermal Channel On(EO channel on : 0, Thermal channel on : 1) | */
   public static final int CHANNEL_MODE_TYPE_ENUM_END = 129; /*  | */
}
            