/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* Radio Channel Bandwidth type
*/
public class CHANNEL_BANDWIDTH {
   public static final int CHANNEL_BANDWIDTH_4MHZ = 0; /* Radio Channel Bandwidth 4MHz | */
   public static final int CHANNEL_BANDWIDTH_8MHZ = 1; /* Radio Channel Bandwidth 8MHz(Default) | */
   public static final int CHANNEL_BANDWIDTH_ENUM_END = 2; /*  | */
}
            