/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* RF Encryption type
*/
public class ENCRYPTION_TYPE {
   public static final int ENCRYPTION_TYPE_NONE = 0; /* RF Encryption None(default) | */
   public static final int ENCRYPTION_TYPE_AES128 = 1; /* RF Encryption AES-128 On | */
   public static final int ENCRYPTION_TYPE_ENUM_END = 2; /*  | */
}
            