/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* EO/IR Camera Mode flags (bitmask)
*/
public class EO_IR_MODE_REPORT_TYPE {
   public static final int EO_IR_REP_RATE_MODE = 0; /* Rate Mode(stablized on) | */
   public static final int EO_IR_REP_PILOT_WINDOW_MODE = 12; /* Pilot Window Mode(stablized off) | */
   public static final int EO_IR_REP_STOW_MODE = 16; /* Stow Mode(stablized off) | */
   public static final int EO_IR_REP_PARK_MODE = 32; /* Park Mode(stablized off) | */
   public static final int EO_IR_REP_CALIBRATION_MODE = 40; /* Calibration Mode(stablized on) | */
   public static final int EO_IR_REP_THERMAL_CHANNEL_ON = 128; /* Thermal Channel On(EO channel on : 0, Thermal channel on : 1) | */
   public static final int EO_IR_MODE_REPORT_TYPE_ENUM_END = 129; /*  | */
}
            