/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* EO/IR Camera Mode flags (bitmask)
*/
public class EO_IR_MODE_TYPE {
   public static final int RATE_MODE = 0; /* Rate Mode(stablized on) | */
   public static final int PILOT_WINDOW_MODE = 3; /* Pilot Window Mode(stablized off) | */
   public static final int STOW_MODE = 4; /* Stow Mode(stablized off) | */
   public static final int PARK_MODE = 8; /* Park Mode(stablized off) | */
   public static final int CALIBRATION_MODE = 10; /* Calibration Mode(stablized on) | */
   public static final int OSD_GRAPHIC_DISPLAY_ON = 32; /* Video Streaming over Graphic Display On(off : 0, on : 1)  | */
   public static final int OSD_TEXT_DISPLAY_ON = 64; /* Video Streaming over Text Display On(off : 0, on : 1) | */
   public static final int EO_IR_MODE_TYPE_ENUM_END = 65; /*  | */
}
            