/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* MIMO On Off Control type
*/
public class MIMO_ON_OFF_TYPE {
   public static final int MIMO_OFF = 0; /* MIMO Off | */
   public static final int MIMO_ON = 1; /* MIMO On(Default) | */
   public static final int MIMO_ON_OFF_TYPE_ENUM_END = 2; /*  | */
}
            