/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* Node Connection type
*/
public class NODE_CON_TYPE {
   public static final int NODE_CON_TYPE_STATIC = 0; /* Static(Default) | */
   public static final int NODE_CON_TYPE_DHCP = 1; /* DHCP | */
   public static final int NODE_CON_TYPE_ENUM_END = 2; /*  | */
}
            