/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* Radio On Off Contrl type
*/
public class RADIO_ON_OFF_TYPE {
   public static final int RADIO_OFF = 0; /* Radio Off | */
   public static final int RADIO_ON = 1; /* Radio On(Default) | */
   public static final int RADIO_ON_OFF_TYPE_ENUM_END = 2; /*  | */
}
            