/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* EO/IR Camera Record Report flags (bitmask)
*/
public class RECORD_REPORT_TYPE {
   public static final int PAUSED = 0; /* Paused | */
   public static final int RECORDING = 16; /* Recording... | */
   public static final int ERROR = 224; /* Error | */
   public static final int MEMORY_FULL = 240; /* Memory Full | */
   public static final int RECORD_REPORT_TYPE_ENUM_END = 241; /*  | */
}
            