/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* EO/IR Camera Record Control flags (bitmask)
*/
public class RECORD_TYPE {
   public static final int RECORD_ON = 16; /* Record On | */
   public static final int SNAPSHOT_ON = 32; /* Snapshot On | */
   public static final int RECORD_TYPE_ENUM_END = 33; /*  | */
}
            