/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* RF Operation Mode type
*/
public class RF_OPERATION_MODE {
   public static final int RF_OPERATION_MODE_MASTER = 0; /* RF Operation Mode Master | */
   public static final int RF_OPERATION_MODE_SLAVE = 1; /* RF Operation Mode Slave(default) | */
   public static final int RF_OPERATION_MODE_ENUM_END = 2; /*  | */
}
            