/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* Atmospheric measurement sensor status flags (bitmask)
*/
public class SENSOR_STATUS_TYPE {
   public static final int GAS_SENSOR_ERROR = 1; /* CO Sensor Data Send Request | */
   public static final int DUST_SENSOR_ERROR = 2; /* SO2 Sensor Data Send Request | */
   public static final int TH_SENSOR_ERROR = 4; /* NO2 Sensor Data Send Request | */
   public static final int AIR_PUMP_ERROR = 8; /* O3 Sensor Data Send Request | */
   public static final int ALL_SENSOR_ERROR = 128; /* PM2.5 Sensor Data Send Request | */
   public static final int SENSOR_STATUS_TYPE_ENUM_END = 129; /*  | */
}
            