/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* Atmospheric measurement sensor data send request flags (bitmask)
*/
public class SENSOR_DATA_SEND_REQ_TYPE {
   public static final int CO_DATA_REQ = 1; /* CO Sensor Data Send Request | */
   public static final int SO2_DATA_REQ = 2; /* SO2 Sensor Data Send Request | */
   public static final int NO2_DATA_REQ = 4; /* NO2 Sensor Data Send Request | */
   public static final int O3_DATA_REQ = 8; /* O3 Sensor Data Send Request | */
   public static final int PM25_DATA_REQ = 16; /* PM2.5 Sensor Data Send Request | */
   public static final int PM10_DATA_REQ = 32; /* PM10 Sensor Data Send Request | */
   public static final int T_H_DATA_REQ = 64; /* TH Sensor Data Send Request | */
   public static final int ALL_DATA_REQ = 128; /* All Sensor Data Send Request | */
   public static final int SENSOR_DATA_SEND_REQ_TYPE_ENUM_END = 129; /*  | */
}
            