/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* Atmospheric measurement sensor power control flags (bitmask)
*/
public class SENSOR_PWR_TYPE {
   public static final int MAIN_PWR_ON = 1; /* Main Power On | */
   public static final int AIR_PUMP_ON = 2; /* Air Pump Power On | */
   public static final int PM_SENSOR_ON = 4; /* PM Sensor Power On | */
   public static final int SENSOR_PWR_TYPE_ENUM_END = 5; /*  | */
}
            