/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* EO/IR Camera Thermal NUC flags (bitmask)
*/
public class THERMAL_NUC_TYPE {
   public static final int PERIODIC_NUC_ON = 0; /* Periodic NUC Activation | */
   public static final int RUN_NUC = 2; /* Run NUC | */
   public static final int PERIODIC_NUC_OFF = 7; /* Disable Periodic NUC | */
   public static final int THERMAL_NUC_TYPE_ENUM_END = 8; /*  | */
}
            