/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* EO/IR Camera Thermal Control flags (bitmask)
*/
public class THERMAL_CTRL_TYPE {
   public static final int DECREASE_LEVEL = 1; /* Decrease Level | */
   public static final int INCREASE_LEVEL = 2; /* Increase Level | */
   public static final int DECREASE_GAIN = 4; /* Decrease Gain | */
   public static final int INCREASE_GAIN = 8; /* Increase Gain | */
   public static final int BLACK_HOT = 64; /* Thermal Polarity(White Hot : 0, Black Hot : 1) | */
   public static final int THERMAL_CTRL_TYPE_ENUM_END = 65; /*  | */
}
            