/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* Radio Tx RF Power type
*/
public class TX_RF_POWER {
   public static final int TX_RF_POWER_7dbm = 7; /* Radio Tx RF Power 7dbm | */
   public static final int TX_RF_POWER_8dbm = 8; /* Radio Tx RF Power 8dbm | */
   public static final int TX_RF_POWER_9dbm = 9; /* Radio Tx RF Power 9dbm | */
   public static final int TX_RF_POWER_10dbm = 10; /* Radio Tx RF Power 10dbm | */
   public static final int TX_RF_POWER_11dbm = 11; /* Radio Tx RF Power 11dbm | */
   public static final int TX_RF_POWER_12dbm = 12; /* Radio Tx RF Power 12dbm | */
   public static final int TX_RF_POWER_13dbm = 13; /* Radio Tx RF Power 13dbm | */
   public static final int TX_RF_POWER_14dbm = 14; /* Radio Tx RF Power 14dbm | */
   public static final int TX_RF_POWER_15dbm = 15; /* Radio Tx RF Power 15dbm | */
   public static final int TX_RF_POWER_16dbm = 16; /* Radio Tx RF Power 16dbm | */
   public static final int TX_RF_POWER_17dbm = 17; /* Radio Tx RF Power 17dbm | */
   public static final int TX_RF_POWER_18dbm = 18; /* Radio Tx RF Power 18dbm | */
   public static final int TX_RF_POWER_19dbm = 19; /* Radio Tx RF Power 19dbm | */
   public static final int TX_RF_POWER_20dbm = 20; /* Radio Tx RF Power 20dbm | */
   public static final int TX_RF_POWER_21dbm = 21; /* Radio Tx RF Power 21dbm | */
   public static final int TX_RF_POWER_22dbm = 22; /* Radio Tx RF Power 22dbm | */
   public static final int TX_RF_POWER_23dbm = 23; /* Radio Tx RF Power 23dbm | */
   public static final int TX_RF_POWER_24dbm = 24; /* Radio Tx RF Power 24dbm | */
   public static final int TX_RF_POWER_25dbm = 25; /* Radio Tx RF Power 25dbm | */
   public static final int TX_RF_POWER_26dbm = 26; /* Radio Tx RF Power 26dbm | */
   public static final int TX_RF_POWER_27dbm = 27; /* Radio Tx RF Power 27dbm | */
   public static final int TX_RF_POWER_28dbm = 28; /* Radio Tx RF Power 28dbm | */
   public static final int TX_RF_POWER_29dbm = 29; /* Radio Tx RF Power 29dbm | */
   public static final int TX_RF_POWER_30dbm = 30; /* Radio Tx RF Power 30dbm | */
   public static final int TX_RF_POWER_ENUM_END = 31; /*  | */
}
            