/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package dji.v5.ux.MAVLink.enums;

/** 
* EO/IR Camera Zoom Control flags (bitmask)
*/
public class ZOOM_TYPE {
   public static final int NO_CHANGE = 0; /* No Change | */
   public static final int ZOOM_OUT = 1; /* Zoom Out | */
   public static final int ZOOM_IN = 2; /* Zoom In | */
   public static final int ZOOM_TYPE_ENUM_END = 3; /*  | */
}
            