/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SENSOR_DATA_REQUEST PACKING
package dji.v5.ux.MAVLink.ardupilotmega;
import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;
        
/**
* Atmospheric Measurement Sensor Data Send Request
*/
public class msg_sensor_data_request extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_SENSOR_DATA_REQUEST = 12010;
    public static final int MAVLINK_MSG_ID_SENSOR_DATA_REQUEST_CRC = 193;
    public static final int MAVLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SENSOR_DATA_REQUEST;


      
    /**
    * Sensor Data Period(reserverd : 0, 1sec:1 ~ 5sec:5)
    */
    public short sensor_data_period;
      
    /**
    * Bitmap of Sensor Data Send Request
    */
    public short sensor_data_send_req;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SENSOR_DATA_REQUEST;
        packet.crc_extra = MAVLINK_MSG_ID_SENSOR_DATA_REQUEST_CRC;
              
        packet.payload.putUnsignedByte(sensor_data_period);
              
        packet.payload.putUnsignedByte(sensor_data_send_req);
        
        return packet;
    }

    /**
    * Decode a sensor_data_request message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.sensor_data_period = payload.getUnsignedByte();
              
        this.sensor_data_send_req = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_sensor_data_request(){
        msgid = MAVLINK_MSG_ID_SENSOR_DATA_REQUEST;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_sensor_data_request(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SENSOR_DATA_REQUEST;
        unpack(mavLinkPacket.payload);
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_SENSOR_DATA_REQUEST - sysid:"+sysid+" compid:"+compid+" sensor_data_period:"+sensor_data_period+" sensor_data_send_req:"+sensor_data_send_req+"";
    }
}
        