/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE REQUEST_SENSOR_STATUS PACKING
package dji.v5.ux.MAVLink.ardupilotmega;
import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;
        
/**
* Atmospheric Measurement Sensor Status Request
*/
public class msg_request_sensor_status extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_REQUEST_SENSOR_STATUS = 12008;
    public static final int MAVLINK_MSG_ID_REQUEST_SENSOR_STATUS_CRC = 162;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_REQUEST_SENSOR_STATUS;


      
    /**
    * Request Sensor Status(request : 1, none : 0)
    */
    public short req_sensort_status;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_REQUEST_SENSOR_STATUS;
        packet.crc_extra = MAVLINK_MSG_ID_REQUEST_SENSOR_STATUS_CRC;
              
        packet.payload.putUnsignedByte(req_sensort_status);
        
        return packet;
    }

    /**
    * Decode a request_sensor_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.req_sensort_status = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_request_sensor_status(){
        msgid = MAVLINK_MSG_ID_REQUEST_SENSOR_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_request_sensor_status(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_REQUEST_SENSOR_STATUS;
        unpack(mavLinkPacket.payload);
    }

      
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_REQUEST_SENSOR_STATUS - sysid:"+sysid+" compid:"+compid+" req_sensort_status:"+req_sensort_status+"";
    }
}
        