/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE PL_RF_HEARTBEAT PACKING
package dji.v5.ux.MAVLink.ardupilotmega;
import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;
        
/**
* 2.4GHz wireless communication RF Heartbeat
*/
public class msg_pl_rf_heartbeat extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_PL_RF_HEARTBEAT = 12005;
    public static final int MAVLINK_MSG_ID_PL_RF_HEARTBEAT_CRC = 87;
    public static final int MAVLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = MAVLINK_MSG_ID_PL_RF_HEARTBEAT;


      
    /**
    * Signal to Noise Ratio
    */
    public short signal2_noise_ratio;
      
    /**
    * RF RSSI
    */
    public short rf_rssi;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_PL_RF_HEARTBEAT;
        packet.crc_extra = MAVLINK_MSG_ID_PL_RF_HEARTBEAT_CRC;
              
        packet.payload.putUnsignedByte(signal2_noise_ratio);
              
        packet.payload.putUnsignedByte(rf_rssi);
        
        return packet;
    }

    /**
    * Decode a pl_rf_heartbeat message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.signal2_noise_ratio = payload.getUnsignedByte();
              
        this.rf_rssi = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_pl_rf_heartbeat(){
        msgid = MAVLINK_MSG_ID_PL_RF_HEARTBEAT;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_pl_rf_heartbeat(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_PL_RF_HEARTBEAT;
        unpack(mavLinkPacket.payload);
    }

        
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_PL_RF_HEARTBEAT - sysid:"+sysid+" compid:"+compid+" signal2_noise_ratio:"+signal2_noise_ratio+" rf_rssi:"+rf_rssi+"";
    }
}
        