/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SENSOR_POWER_REPORT PACKING
package dji.v5.ux.MAVLink.ardupilotmega;
import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;
        
/**
* Atmospheric Measurement Sensor Power Staus
*/
public class msg_sensor_power_report extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_SENSOR_POWER_REPORT = 12012;
    public static final int MAVLINK_MSG_ID_SENSOR_POWER_REPORT_CRC = 166;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SENSOR_POWER_REPORT;


      
    /**
    * Bitmap of Sensor Power Status Report
    */
    public short sensor_power_status;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SENSOR_POWER_REPORT;
        packet.crc_extra = MAVLINK_MSG_ID_SENSOR_POWER_REPORT_CRC;
              
        packet.payload.putUnsignedByte(sensor_power_status);
        
        return packet;
    }

    /**
    * Decode a sensor_power_report message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.sensor_power_status = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_sensor_power_report(){
        msgid = MAVLINK_MSG_ID_SENSOR_POWER_REPORT;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_sensor_power_report(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SENSOR_POWER_REPORT;
        unpack(mavLinkPacket.payload);
    }

      
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_SENSOR_POWER_REPORT - sysid:"+sysid+" compid:"+compid+" sensor_power_status:"+sensor_power_status+"";
    }
}
        