package dji.v5.ux.MAVLink.ardupilotmega;

import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
*
* This class was automatically generated by the
* java mavlink generator tool. It should not be modified by hand.
*/

//MESSAGE GIMBAL_RGBLAB PACKING
       
/**
* GimbalControlRGBLAB
*/
public class msg_gimbal_rgblab extends MAVLinkMessage{

   public static final int MAVLINK_MSG_ID_GIMBAL_RGBLAB = 424;
   public static final int MAVLINK_MSG_LENGTH = 5;
   public static final int MAVLINK_MSG_ID_GIMBAL_RGBLAB_CRC = 147;
   private static final long serialVersionUID = MAVLINK_MSG_ID_GIMBAL_RGBLAB;


     
   /**
   * gimbal_yaw
   */
   public int gimbal_yaw;
     
   /**
   * gimbal_roll
   */
   public short gimbal_roll;
     
   /**
   * gimbal_pitch
   */
   public short gimbal_pitch;
     
   /**
   * zero_prevention
   */
   public short zero_prevention;
   

   /**
   * Generates the payload for a mavlink message for a message of this type
   * @return
   */
   public MAVLinkPacket pack(){
       MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
       packet.sysid = 255;
       packet.compid = 190;
       packet.msgid = MAVLINK_MSG_ID_GIMBAL_RGBLAB;
       packet.crc_extra = MAVLINK_MSG_ID_GIMBAL_RGBLAB_CRC;
             
       packet.payload.putUnsignedShort(gimbal_yaw);
             
       packet.payload.putUnsignedByte(gimbal_roll);
             
       packet.payload.putUnsignedByte(gimbal_pitch);
             
       packet.payload.putUnsignedByte(zero_prevention);
       
       return packet;
   }

   /**
   * Decode a gimbal_rgblab message into this class fields
   *
   * @param payload The message to decode
   */
   public void unpack(MAVLinkPayload payload) {
       payload.resetIndex();
             
       this.gimbal_yaw = payload.getUnsignedShort();
             
       this.gimbal_roll = payload.getUnsignedByte();
             
       this.gimbal_pitch = payload.getUnsignedByte();
             
       this.zero_prevention = payload.getUnsignedByte();
       
   }

   /**
   * Constructor for a new message, just initializes the msgid
   */
   public msg_gimbal_rgblab(){
       msgid = MAVLINK_MSG_ID_GIMBAL_RGBLAB;
   }

   /**
   * Constructor for a new message, initializes the message with the payload
   * from a mavlink packet
   *
   */
   public msg_gimbal_rgblab(MAVLinkPacket mavLinkPacket){
       this.sysid = mavLinkPacket.sysid;
       this.compid = mavLinkPacket.compid;
       this.msgid = MAVLINK_MSG_ID_GIMBAL_RGBLAB;
       unpack(mavLinkPacket.payload);        
   }

           
   /**
   * Returns a string with the MSG name and data
   */
   public String toString(){
       return "MAVLINK_MSG_ID_GIMBAL_RGBLAB - sysid:"+sysid+" compid:"+compid+" gimbal_yaw:"+gimbal_yaw+" gimbal_roll:"+gimbal_roll+" gimbal_pitch:"+gimbal_pitch+" zero_prevention:"+zero_prevention+"";
   }
}
       