package dji.v5.ux.MAVLink.ardupilotmega;

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE CHANNEL_HEARTBEAT PACKING
import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;
        
/**
 * Channel Heartbeat.
 */
public class msg_channel_heartbeat extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_CHANNEL_HEARTBEAT = 229;
    public static final int MAVLINK_MSG_LENGTH = 3;
    public static final int MAVLINK_MSG_ID_CHANNEL_HEARTBEAT_CRC = 155;
    private static final long serialVersionUID = MAVLINK_MSG_ID_CHANNEL_HEARTBEAT;

//    MAVLINK_MESSAGE_CRCS.put(228, 249);
//    MAVLINK_MESSAGE_CRCS.put(229, 134);
      
    /**
     * 
     */
    public int heartbeat_seq;
      
    /**
     * 
     */
    public short zero_prevention;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_CHANNEL_HEARTBEAT;
        packet.crc_extra = MAVLINK_MSG_ID_CHANNEL_HEARTBEAT_CRC;
        
        packet.payload.putUnsignedShort(heartbeat_seq);    
        
        packet.payload.putUnsignedByte(zero_prevention);    
        
        return packet;
    }

    /**
     * Decode a channel_heartbeat message into this class fields
     *
     * @param payload The message to decode
     */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.heartbeat_seq = payload.getUnsignedShort();    
        
        this.zero_prevention = payload.getUnsignedByte();    
        
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_channel_heartbeat() {
        msgid = MAVLINK_MSG_ID_CHANNEL_HEARTBEAT;
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_channel_heartbeat(MAVLinkPacket mavLinkPacket) {
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_CHANNEL_HEARTBEAT;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    public String toString() {
        return "MAVLINK_MSG_ID_CHANNEL_HEARTBEAT - sysid:"+sysid+" compid:"+compid+" heartbeat_seq:"+heartbeat_seq+" zero_prevention:"+zero_prevention+"";
    }
}
        