/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SENSOR_DATA_REPORT PACKING
package dji.v5.ux.MAVLink.ardupilotmega;
import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;
        
/**
* Atmospheric Measurement Sensor Data Report
*/
public class msg_sensor_data_report extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_SENSOR_DATA_REPORT = 12013;
    public static final int MAVLINK_MSG_ID_SENSOR_DATA_REPORT_CRC = 12;
    public static final int MAVLINK_MSG_LENGTH = 16;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SENSOR_DATA_REPORT;


      
    /**
    * CO Data LSB
    */
    public short co_data_lsb;
      
    /**
    * CO Data MSB
    */
    public short co_data_msb;
      
    /**
    * SO2 Data LSB
    */
    public short so2_data_lsb;
      
    /**
    * SO2 Data MSB
    */
    public short so2_data_msb;
      
    /**
    * NO2 Data LSB
    */
    public short no2_data_lsb;
      
    /**
    * NO2 Data MSB
    */
    public short no2_data_msb;
      
    /**
    * O3 Data LSB
    */
    public short o3_data_lsb;
      
    /**
    * O3 Data MSB
    */
    public short o3_data_msb;
      
    /**
    * PM2.5 Data LSB
    */
    public short pm25_data_lsb;
      
    /**
    * PM2.5 Data MSB
    */
    public short pm25_data_msb;
      
    /**
    * PM10 Data LSB
    */
    public short pm10_data_lsb;
      
    /**
    * PM10 Data MSB
    */
    public short pm10_data_msb;
      
    /**
    * Temperature Data LSB
    */
    public short temperature_data_lsb;
      
    /**
    * Temperature Data MSB
    */
    public short temperature_data_msb;
      
    /**
    * Humidity Data LSB
    */
    public short humidity_data_lsb;
      
    /**
    * Humidity Data MSB
    */
    public short humidity_data_msb;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SENSOR_DATA_REPORT;
        packet.crc_extra = MAVLINK_MSG_ID_SENSOR_DATA_REPORT_CRC;
              
        packet.payload.putUnsignedByte(co_data_lsb);
              
        packet.payload.putUnsignedByte(co_data_msb);
              
        packet.payload.putUnsignedByte(so2_data_lsb);
              
        packet.payload.putUnsignedByte(so2_data_msb);
              
        packet.payload.putUnsignedByte(no2_data_lsb);
              
        packet.payload.putUnsignedByte(no2_data_msb);
              
        packet.payload.putUnsignedByte(o3_data_lsb);
              
        packet.payload.putUnsignedByte(o3_data_msb);
              
        packet.payload.putUnsignedByte(pm25_data_lsb);
              
        packet.payload.putUnsignedByte(pm25_data_msb);
              
        packet.payload.putUnsignedByte(pm10_data_lsb);
              
        packet.payload.putUnsignedByte(pm10_data_msb);
              
        packet.payload.putUnsignedByte(temperature_data_lsb);
              
        packet.payload.putUnsignedByte(temperature_data_msb);
              
        packet.payload.putUnsignedByte(humidity_data_lsb);
              
        packet.payload.putUnsignedByte(humidity_data_msb);
        
        return packet;
    }

    /**
    * Decode a sensor_data_report message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.co_data_lsb = payload.getUnsignedByte();
              
        this.co_data_msb = payload.getUnsignedByte();
              
        this.so2_data_lsb = payload.getUnsignedByte();
              
        this.so2_data_msb = payload.getUnsignedByte();
              
        this.no2_data_lsb = payload.getUnsignedByte();
              
        this.no2_data_msb = payload.getUnsignedByte();
              
        this.o3_data_lsb = payload.getUnsignedByte();
              
        this.o3_data_msb = payload.getUnsignedByte();
              
        this.pm25_data_lsb = payload.getUnsignedByte();
              
        this.pm25_data_msb = payload.getUnsignedByte();
              
        this.pm10_data_lsb = payload.getUnsignedByte();
              
        this.pm10_data_msb = payload.getUnsignedByte();
              
        this.temperature_data_lsb = payload.getUnsignedByte();
              
        this.temperature_data_msb = payload.getUnsignedByte();
              
        this.humidity_data_lsb = payload.getUnsignedByte();
              
        this.humidity_data_msb = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_sensor_data_report(){
        msgid = MAVLINK_MSG_ID_SENSOR_DATA_REPORT;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_sensor_data_report(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SENSOR_DATA_REPORT;
        unpack(mavLinkPacket.payload);
    }

                                    
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_SENSOR_DATA_REPORT - sysid:"+sysid+" compid:"+compid+" co_data_lsb:"+co_data_lsb+" co_data_msb:"+co_data_msb+" so2_data_lsb:"+so2_data_lsb+" so2_data_msb:"+so2_data_msb+" no2_data_lsb:"+no2_data_lsb+" no2_data_msb:"+no2_data_msb+" o3_data_lsb:"+o3_data_lsb+" o3_data_msb:"+o3_data_msb+" pm25_data_lsb:"+pm25_data_lsb+" pm25_data_msb:"+pm25_data_msb+" pm10_data_lsb:"+pm10_data_lsb+" pm10_data_msb:"+pm10_data_msb+" temperature_data_lsb:"+temperature_data_lsb+" temperature_data_msb:"+temperature_data_msb+" humidity_data_lsb:"+humidity_data_lsb+" humidity_data_msb:"+humidity_data_msb+"";
    }
}
        