/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SENSOR_POWER_CONTROL PACKING
package dji.v5.ux.MAVLink.ardupilotmega;
import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;
        
/**
* Atmospheric Measurement Sensor Power Control
*/
public class msg_sensor_power_control extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_SENSOR_POWER_CONTROL = 12009;
    public static final int MAVLINK_MSG_ID_SENSOR_POWER_CONTROL_CRC = 105;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SENSOR_POWER_CONTROL;


      
    /**
    * Bitmap of Sensor Power Control
    */
    public short sensor_power_control;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SENSOR_POWER_CONTROL;
        packet.crc_extra = MAVLINK_MSG_ID_SENSOR_POWER_CONTROL_CRC;
              
        packet.payload.putUnsignedByte(sensor_power_control);
        
        return packet;
    }

    /**
    * Decode a sensor_power_control message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.sensor_power_control = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_sensor_power_control(){
        msgid = MAVLINK_MSG_ID_SENSOR_POWER_CONTROL;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_sensor_power_control(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SENSOR_POWER_CONTROL;
        unpack(mavLinkPacket.payload);
    }

      
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_SENSOR_POWER_CONTROL - sysid:"+sysid+" compid:"+compid+" sensor_power_control:"+sensor_power_control+"";
    }
}
        