package dji.v5.ux.MAVLink.ardupilotmega;

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SET_CHANNEL PACKING
import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;
        
/**
 * SET_CHANNEL output.
 */
public class msg_set_channel extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SET_CHANNEL = 228;
    public static final int MAVLINK_MSG_LENGTH = 3;
    public static final int MAVLINK_MSG_ID_SET_CHANNEL_CRC = 249;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SET_CHANNEL;


      
    /**
     * Channel ID.
     */
    public int channel_id;
      
    /**
     * 189.
     */
    public short zero_prevention;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_SET_CHANNEL;
        packet.crc_extra = MAVLINK_MSG_ID_SET_CHANNEL_CRC;
        
        packet.payload.putUnsignedShort(channel_id);    
        
        packet.payload.putUnsignedByte(zero_prevention);    
        
        return packet;
    }

    /**
     * Decode a set_channel message into this class fields
     *
     * @param payload The message to decode
     */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.channel_id = payload.getUnsignedShort();    
        
        this.zero_prevention = payload.getUnsignedByte();    
        
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_set_channel() {
        msgid = MAVLINK_MSG_ID_SET_CHANNEL;
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_set_channel(MAVLinkPacket mavLinkPacket) {
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_SET_CHANNEL;
        unpack(mavLinkPacket.payload);        
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    public String toString() {
        return "MAVLINK_MSG_ID_SET_CHANNEL - sysid:"+sysid+" compid:"+compid+" channel_id:"+channel_id+" zero_prevention:"+zero_prevention+"";
    }
}
        