package dji.v5.ux.MAVLink.ardupilotmega;

import dji.v5.ux.MAVLink.MAVLinkPacket;
import dji.v5.ux.MAVLink.Messages.MAVLinkMessage;
import dji.v5.ux.MAVLink.Messages.MAVLinkPayload;

/* AUTO-GENERATED FILE.  DO NOT MODIFY.
*
* This class was automatically generated by the
* java mavlink generator tool. It should not be modified by hand.
*/

//MESSAGE DUMMY_MSG PACKING
       
/**
* DummyMessage
*/
public class msg_dummy_msg extends MAVLinkMessage{

   public static final int MAVLINK_MSG_ID_DUMMY_MSG = 426;
   public static final int MAVLINK_MSG_LENGTH = 88;
   public static final int MAVLINK_MSG_ID_DUMMY_MSG_CRC = 26;
   private static final long serialVersionUID = MAVLINK_MSG_ID_DUMMY_MSG;


     
   /**
   * dummy1
   */
   public long dummy1;
     
   /**
   * dummy2
   */
   public long dummy2;
     
   /**
   * dummy3
   */
   public long dummy3;
     
   /**
   * dummy4
   */
   public long dummy4;
     
   /**
   * dummy5
   */
   public long dummy5;
     
   /**
   * dummy6
   */
   public long dummy6;
     
   /**
   * dummy7
   */
   public long dummy7;
     
   /**
   * dummy8
   */
   public long dummy8;
     
   /**
   * dummy9
   */
   public long dummy9;
     
   /**
   * dummy10
   */
   public long dummy10;
     
   /**
   * dummy11
   */
   public long dummy11;
   

   /**
   * Generates the payload for a mavlink message for a message of this type
   * @return
   */
   public MAVLinkPacket pack(){
       MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
       packet.sysid = 255;
       packet.compid = 190;
       packet.msgid = MAVLINK_MSG_ID_DUMMY_MSG;
       packet.crc_extra = MAVLINK_MSG_ID_DUMMY_MSG_CRC;
             
       packet.payload.putUnsignedLong(dummy1);
             
       packet.payload.putUnsignedLong(dummy2);
             
       packet.payload.putUnsignedLong(dummy3);
             
       packet.payload.putUnsignedLong(dummy4);
             
       packet.payload.putUnsignedLong(dummy5);
             
       packet.payload.putUnsignedLong(dummy6);
             
       packet.payload.putUnsignedLong(dummy7);
             
       packet.payload.putUnsignedLong(dummy8);
             
       packet.payload.putUnsignedLong(dummy9);
             
       packet.payload.putUnsignedLong(dummy10);
             
       packet.payload.putUnsignedLong(dummy11);
       
       return packet;
   }

   /**
   * Decode a dummy_msg message into this class fields
   *
   * @param payload The message to decode
   */
   public void unpack(MAVLinkPayload payload) {
       payload.resetIndex();
             
       this.dummy1 = payload.getUnsignedLong();
             
       this.dummy2 = payload.getUnsignedLong();
             
       this.dummy3 = payload.getUnsignedLong();
             
       this.dummy4 = payload.getUnsignedLong();
             
       this.dummy5 = payload.getUnsignedLong();
             
       this.dummy6 = payload.getUnsignedLong();
             
       this.dummy7 = payload.getUnsignedLong();
             
       this.dummy8 = payload.getUnsignedLong();
             
       this.dummy9 = payload.getUnsignedLong();
             
       this.dummy10 = payload.getUnsignedLong();
             
       this.dummy11 = payload.getUnsignedLong();
       
   }

   /**
   * Constructor for a new message, just initializes the msgid
   */
   public msg_dummy_msg(){
       msgid = MAVLINK_MSG_ID_DUMMY_MSG;
   }

   /**
   * Constructor for a new message, initializes the message with the payload
   * from a mavlink packet
   *
   */
   public msg_dummy_msg(MAVLinkPacket mavLinkPacket){
       this.sysid = mavLinkPacket.sysid;
       this.compid = mavLinkPacket.compid;
       this.msgid = MAVLINK_MSG_ID_DUMMY_MSG;
       unpack(mavLinkPacket.payload);        
   }

                         
   /**
   * Returns a string with the MSG name and data
   */
   public String toString(){
       return "MAVLINK_MSG_ID_DUMMY_MSG - sysid:"+sysid+" compid:"+compid+" dummy1:"+dummy1+" dummy2:"+dummy2+" dummy3:"+dummy3+" dummy4:"+dummy4+" dummy5:"+dummy5+" dummy6:"+dummy6+" dummy7:"+dummy7+" dummy8:"+dummy8+" dummy9:"+dummy9+" dummy10:"+dummy10+" dummy11:"+dummy11+"";
   }
}
       